CREATE TABLE IF NOT EXISTS produtos (
    id SERIAL PRIMARY KEY,
    pr INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    modelo INTEGER NOT NULL,
    problema TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
